### ISSUE TITLE
Unable to load competiton

### ISSUE THREAD

**Issue by Sujiah** [TeamFluXServers/giveaway#1]
Hi there,

When I click on the link you provided on the wiki (http://www.teamfluxservers.co.uk/pages/giveaway) it says "Loading..." and then says "Unable to load competition, please try again later."

Any idea's?

Thank's

**Comment by TeamFluXServers** [comment]
Hi there Sujiah,

What browser are you using?
After you tell me your browser I will be able to further assist you with your issue.
Thank you,

Team FluX Server's

**Comment by Sujiah** [comment]
I am using Mozilla FireFox

Thank's Team FluX

**Comment by TeamFluXServers** [comment]
Hello once again Sujiah,

The HTML code we use is not supported by Mozilla FireFox yet. The Team FluX Support team have been notified of your issue and they are going to fix it within the next 24 hours. Until then you can use any other browser and it will work fine, or alternatively you can wait for the issue to be fixed.

Thank you,

Team FluX Server's

**Comment by Sujiah** [comment]
That's great, thanks so much.

**Comment by TeamFluXServers** [comment]
Issue has now been locked, if you have any other issues please open a new issue, thank you.
